@startuml

!include ../../../../defaults.iuml

FA_LAPTOP(Client,Client,participant)
FA_USER(User,User,participant)
FA5_HTML5(Application,Application,participant)
FA5_SERVER(Server,Server,participant)
GOV_KEY(Authenticator,Authenticator,participant)

title FIDO Based Authentication Failure Due To Policy

autonumber
group Authentication Event
    User -> Client: User navigates to website
    Client -> Application: Submits request for page
    Application -> Application: No user session
    Application -> Client: Redirects to $fido_url
    Client -> Server: Client requests login page
    Server -> Client: Returns login page
    Client -> Client: Enters email address or username
    Client -> Client: Clicks next button
    Client  -> Server: Credential sent with context data
    Server -> Server: Looks up if strong\nauthenticator registered
    Client -> Server: Get challenge
    Server -> Client: Challenge
    Client -> Authenticator: Authorization request sent
    Authenticator -> Authenticator: Prompt or notification,\n"Sign in to $fido_url"
    User -> Authenticator: Approves prompt for sign in
    User -> Authenticator: Enters PIN (if required)
    User -> Authenticator: Asserts authorization gesture
    Authenticator -> Client: Signed challenge
    Client -> Server: Signed challenge
    Server -> Server: Validates challenge with public key
    Server -> Server: Validates user and key pairs
    Server -> Server: Evaluates against security policies
    Server -> Server: Policy Evaluation Fails
    Server -> Client: Redirects to username / password page
end

@enduml