@startuml

!include ../../../defaults.iuml

title OPA Architecture

actor Consumer

node "OPA Architecture Components" {
  node "Discovery Service" as ds
  node "Open Policy Agent"
  node "Bundle Service"
  node "Agent Telemetry"
  node "Decision Log Service"
  node "Platform Monitoring"
}

/'
node "Policy Owner" {
  node "Owner Bundle Service"
  node "Policy (Rego)"
  node "Data (JSON)"
} '/

[Consumer] -r-> [Open Policy Agent] : Query Policy
[Open Policy Agent] -u-> [ds] : Download Configuration\n(Discovery API)
[Open Policy Agent] -u-> [Bundle Service] : Download Policies & Data Bundles\n(Bundle API)
[Open Policy Agent] <-u- [Platform Monitoring] : Collect Performance Metrics\n(Health API)
[Open Policy Agent] -d-> [Agent Telemetry] : Status Notifications\n(Status API)
[Open Policy Agent] -d-> [Decision Log Service] : Decision Logs\n(Decision Log API)


@enduml